# Exercise 1: NumPy: Create an array with values ranging from 12 to 38¶

In [2]:
import numpy as np

In [4]:
arr=np.array(range(12,39))
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

# Exercise 2: Add a border around an existing array

In [8]:
arr_ones=np.ones([3,3])
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.pad(arr_ones,(1,1),'constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# Exercise 3: Convert a list and tuple into arrays

In [5]:
lst_sample=[1,2,3,4,5,6,7,8]
arr1=np.array(lst_sample)
print('List to Array:',arr1)

List to Array: [1 2 3 4 5 6 7 8]


In [6]:
arr2=np.asarray(lst_sample)
arr2
print('List to Array using asArray:',arr2)

List to Array using asArray: [1 2 3 4 5 6 7 8]


In [11]:
tup_sample=(8,4,6,1,2,3)
print("Tuple to Array:\n",np.array(tup_sample).reshape(2,3))

Tuple to Array:
 [[8 4 6]
 [1 2 3]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees

In [47]:
Fah_values=np.array([0,12,45.21,34,99.91])
Cel_values=(Fah_values-32)*(5/9)
print("Fahrenheit to Centigrade:",Cel_values)

Fahrenheit to Centigrade: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [32]:
array_sample=np.array(range(1,4),dtype='int64')      # or use dtype='float'
print("Number of elements in Array:",len(array_sample))     #use array_sample.size() also
print("1 Element Byte size:",array_sample.itemsize)
print("Total Bytes consumed",array_sample.nbytes)

Number of elements in Array: 3
1 Element Byte size: 8
Total Bytes consumed 24


# Exercise 6: Get the unique elements of an array¶

In [64]:
org_array_first=np.array([10,10,20,20,30,30])
print("First Unique Array:",np.unique(org_array_first))

First Unique Array: [10 20 30]


In [67]:
org_array_second=np.array([[1,1],[2,3]])
print("Second Unique Array:",np.unique(org_array_second))

Second Unique Array: [1 2 3]


# Exercise 7: Change the dimension of an array¶

In [72]:
org_array=np.array(range(1,10))
print("Reshaped array:\n",np.reshape(org_array,(3,3)))

Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [78]:
array1d=np.linspace(2.5,6.5,30)
print("30 evenly Spaced Elements: \n",array1d)

30 evenly Spaced Elements: 
 [2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


# Exercise 9: Convert 1-D arrays as columns into a 2-D array¶

In [23]:
arr1=np.array(range(10,31,10))
arr2=np.array(range(40,61,10))
print("1st Array:",arr1)
print("2nd Array:",arr2)

1st Array: [10 20 30]
2nd Array: [40 50 60]


In [24]:
arr_final=np.column_stack((arr1,arr2))
arr_final

array([[10, 40],
       [20, 50],
       [30, 60]])

# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4¶

In [19]:
org_array=np.zeros([5,5],dtype=int)
print("Original Array:\n",org_array)

Original Array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:

r=5
c=5
for i in range(r):
    for j in range(c):
        org_array[i,j]=j
print("Modified Array:\n",org_array)

Modified Array:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Exercise 11: Sum of all the multiples of 3 or 5 below 100¶

In [112]:
org_array=np.array(range(0,100))
#org_array = np.arange(1,100)
j=0
for i in org_array:
    if((i%3 ==0) or (i%5==0)):
        j=j+i
    else:
        continue
print("Sum of all Multiples of 3 or 5 below 100:",j)

Sum of all Multiples of 3 or 5 below 100: 2318


# Exercise 12: Combine a one and a two dimensional array together and display their elements¶

In [14]:
import numpy as np
x=np.arange(4)
print("1D array:\n",x)
y=np.arange(8).reshape(2,4)
print("2D array:\n",y)
print("Output:\n")
for i,j in np.nditer([x,y]):
    print(i,",",j)

1D array:
 [0 1 2 3]
2D array:
 [[0 1 2 3]
 [4 5 6 7]]
Output:

0 , 0
1 , 1
2 , 2
3 , 3
0 , 4
1 , 5
2 , 6
3 , 7


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.¶

In [10]:
org_array=np.array([[0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701,0.38213418],[0.5097581,0.34528799,0.1563123]])
org_array

array([[0.42436315, 0.48558583, 0.32924763],
       [0.7439979 , 0.58220701, 0.38213418],
       [0.5097581 , 0.34528799, 0.1563123 ]])

In [13]:
org_array[org_array>0.5] =0.5
print("New Array is:\n",org_array)

New Array is:
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


# Exercise 14: Add a new row to an empty numpy array¶

In [8]:
import numpy as np
arr=np.empty([0,3]) # this results in 0 for 3 elements in each row
arr_final=np.append(arr,np.array([[10,20,30],[40,50,60]]),axis=0)
print("Empty Array:\n",arr)
arr_final

Empty Array:
 []


array([[10., 20., 30.],
       [40., 50., 60.]])

# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.¶

In [22]:
arr1=np.array(range(1,4))
arr2=np.array(range(2,5))
print("1st Array:\n",arr1,"\n 2nd Array:\n",arr2)
arr3=np.vstack((arr1,arr2))
print("3rd New Array:\n",arr3)

1st Array:
 [1 2 3] 
 2nd Array:
 [2 3 4]
3rd New Array:
 [[1 2 3]
 [2 3 4]]


In [26]:
arr4=np.array(range(1,4)).reshape(3,1)
arr5=np.array(range(2,5)).reshape(3,1)
print("4th Array:\n",arr4,"\n 5th Array:\n",arr5)
arr6=np.vstack((arr4,arr5))
print("6th New Array:\n",arr6)

4th Array:
 [[1]
 [2]
 [3]] 
 5th Array:
 [[2]
 [3]
 [4]]
6th New Array:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
