In [1]:
 earnings = [ [
     [500,505,490], [810,450,678], [234,897,430], [560,1023,640] 
              ],
             [
                 [600,605,490], [345,900,1000], [780,730,710], [670,540,324] 
             ] ] 

In [3]:
earnings.shape()

AttributeError: 'list' object has no attribute 'shape'

In [7]:
import pandas as pd
import numpy as np

In [8]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'], 'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3], 'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']} 


In [9]:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 

In [14]:
df = pd.DataFrame(data, index=labels)

In [18]:
df.loc[:, ['animal', 'age']],

(  animal  age
 a    cat  2.5
 b    cat  3.0
 c  snake  0.5
 d    dog  NaN
 e    dog  5.0
 f    cat  2.0
 g  snake  4.5
 h    cat  NaN
 i    dog  7.0
 j    dog  3.0,)

In [19]:
df.loc['f', 'age'] = 1.5

In [20]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [30]:
df.groupby('animal').agg({'age':np.mean})

age
animal          
cat     2.333333
dog     5.000000
snake   2.500000

In [31]:
df.groupby('animal').count().shape

(3, 3)

In [32]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
np.range(10,50)

AttributeError: module 'numpy' has no attribute 'range'

In [37]:
list(filter(lambda x:x>5,range(8)))


[6, 7]

In [40]:
a=set((1,2,3,4))
a

{1, 2, 3, 4}

In [41]:
set([[1,2],[3,4]])

TypeError: unhashable type: 'list'

In [42]:
set([1,2,2,3,4])

{1, 2, 3, 4}

In [43]:
x = ['ab', 'cd’] 
print(len(map(list, x)))

SyntaxError: invalid character in identifier (<ipython-input-43-b18b9556c8e3>, line 1)

In [1]:
print('*', "abcde".center(6), '*', sep='')


*abcde *


In [2]:
 x = ['ab', 'cd']
print(len(list(map(list, x))))

2


In [3]:
def small(x):
    i=2
    while(True):
        if(x%i==0):
            return i
        break
print(small(5))

IndentationError: expected an indented block (<ipython-input-3-531801a2f4c8>, line 5)